### ISSUE TITLE
Could you please provide the data set

### ISSUE THREAD

**Issue by 13238830608my** [tahsin314/Lymph_Node_Segmentation#2]
Hi. 
Thank you for your excellent work. Recently, I am studying lymph node segmentation and trying to implement it. I want to learn more about lymph node detection and segmentation by learning and practicing your article. Could you please share your dataset with me ? I will be deeply grateful. 
 
Best wishes. 
A bright moon

**Comment by tahsin314** [comment]
Thanks for the feedback. Unfortunately, the data copyright belongs to the lab we collaborated with, and they did not make it public yet, so I cannot share them with you. However, there is an amazing public LN dataset available [here](https://www.cancerimagingarchive.net/collection/ct-lymph-nodes/) that you can use, and the quality is really good. I hope that helps.
